CREATE TABLE DOCKERTEST.USERS (
		USR_ID DECIMAL(18,0) IDENTITY 254734 NOT NULL,
		USR_NAME VARCHAR(100) UTF8 NOT NULL
);

IMPORT into DOCKERTEST.USERS from local CSV file './data/USERS.csv' SKIP = 1 ENCODING = 'UTF-8';